import type { Product } from "../types/product";

export const mockProducts: Product[] = [
  {
    id: 1,
    seller: { id: "seller1", username: "Seller1" },
    name: 'Laptop Gaming HP - Victus 16.1"',
    description: "Laptop gaming chất lượng cao",
    category: { id: 1, name: "Laptop" },
    price: 30000000,
    stock: 10,
    status: "active",
    attributes: [{ attributeName: "RAM", attributeValue: "16GB" }],
    images: [{ url: "https://product.hstatic.net/200000456405/product/2_9b9f1fcbe69347fbbf57fe18102c2207_1024x1024.png" }],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    seller: { id: "seller2", username: "Seller2" },
    name: 'Laptop Gaming Dell - G15 15.6"',
    description: "Laptop gaming Dell",
    category: { id: 1, name: "Laptop" },
    price: 30000000,
    stock: 5,
    status: "active",
    attributes: [{ attributeName: "CPU", attributeValue: "Intel i7" }],
    images: [{ url: "https://laptopaz.vn/media/lib/2655_345.jpg" }],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3,
    seller: { id: "seller3", username: "Seller3" },
    name: "Case máy tính ASUS - ROG",
    description: "Case máy tính ASUS",
    category: { id: 2, name: "Case" },
    price: 30000000,
    stock: 3,
    status: "active",
    attributes: [{ attributeName: "Material", attributeValue: "Plastic" }],
    images: [{ url: "https://product.hstatic.net/1000233206/product/h732__4__c83daa3366414d7a9ca7025ac2a6b0a8_grande.png" }],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 4,
    seller: { id: "seller4", username: "Seller4" },
    name: 'Màn hình Gaming Acer - Nitro 27"',
    description: "Màn hình gaming Acer",
    category: { id: 3, name: "Monitor" },
    price: 30000000,
    stock: 7,
    status: "active",
    attributes: [{ attributeName: "Resolution", attributeValue: "Full HD" }],
    images: [{ url: "https://cdnv2.tgdd.vn/mwg-static/tgdd/Products/Images/5697/361531/acer-gaming-nitro-27-inch-full-hd-ed270-x-den-2-639029419340752797-750x500.jpg" }],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5,
    seller: { id: "seller5", username: "Seller5" },
    name: 'Laptop Gaming HP - Victus 16.1"',
    description: "Laptop gaming HP",
    category: { id: 1, name: "Laptop" },
    price: 30000000,
    stock: 2,
    status: "active",
    attributes: [{ attributeName: "Storage", attributeValue: "512GB SSD" }],
    images: [{ url: "https://product.hstatic.net/200000456405/product/2_9b9f1fcbe69347fbbf57fe18102c2207_1024x1024.png" }],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];